[features]
seeds = false
[programs.localnet]
anchor_escrow = "5ysMCsoBBWvSjVXhnVFVoebygBNEBJg5mN9ZrrHbjLKE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/karol/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
